# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'cnnct' do
source 'https://github.com/CocoaPods/Specs.git'

pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Firebase/Crash'
pod 'JSQMessagesViewController'
pod 'ColorMatchTabs', '~> 2.0'
end
